### Dato un problema test di dimensioni variabili Ax = b la cui soluzione esatta è il vettore x ̄ = (1, . . . , 1)T e b è il termine noto, ottenuto come Ax ̄ calcolare:
### • il numero di condizionamento della matrice A
### • la soluzione x del sistema lineare Ax = b mediante la fattorizzazione di Cholesky
### Considerare come matrice A la matrice tridiagonale simmetrica definita positiva, avente sulla diagonale principale elementi uguali a 9 ed elementi nella sopra e sottodiagonale uguali a -4, con n variabile.

In [1]:
import numpy as np
import scipy.linalg

n = 4
A = np.eye(n)*9 - np.eye(n, k = -1)*4 - np.eye(n, k = 1)*4
x = np.ones((n, 1))
b = A@x

print("\nA.shape: ", A.shape)
print("x.shape: ",x.shape)
print("b.shape: ", b.shape)


A.shape:  (4, 4)
x.shape:  (4, 1)
b.shape:  (4, 1)


In [2]:
CondA = np.linalg.cond(A, 2)
print("\nK(A)= ", CondA)


K(A)=  6.120636109999744


In [3]:
L = scipy.linalg.cholesky(A, lower = True)

print("\nL = ", L)
print("\nL*L.T = ", np.matmul(L, np.transpose(L)))
print('\nErrore fattorizzazione Cholesky = ', scipy.linalg.norm(A-np.matmul(L, np.transpose(L)), 'fro'))


L =  [[ 3.          0.          0.          0.        ]
 [-1.33333333  2.68741925  0.          0.        ]
 [ 0.         -1.48841682  2.60472943  0.        ]
 [ 0.          0.         -1.53566814  2.57715412]]

L*L.T =  [[ 9. -4.  0.  0.]
 [-4.  9. -4.  0.]
 [ 0. -4.  9. -4.]
 [ 0.  0. -4.  9.]]

Errore fattorizzazione Cholesky =  2.5121479338940403e-15


In [4]:
y = scipy.linalg.solve_triangular(L, b, lower = True)
my_x = scipy.linalg.solve(np.transpose(L), y, lower = False)

print('\nmy_x = \n ', my_x)
print("\nNorma dell'errore =", np.linalg.norm(x-my_x, 'fro'))


my_x = 
  [[1.]
 [1.]
 [1.]
 [1.]]

Norma dell'errore = 3.1401849173675503e-16
